version: "3"
services:
        web:
                image: chasefarmer94/rumbaugh-art-app:prod
                ports:
                        - 80:80
        api:
                build: ./server
                ports:
                        - 8081:80
                links:
                        - "lychee:lychee"
                env_file:
                        - .env
        lychee:
                build: ./lychee
                ports:
                        - 8080:80
                links:
                        - "mysql:mysql"
        mysql:
                build: ./db
                command: --default-authentication-plugin=mysql_native_password
                ports:
                        - 3306:3306
                env_file:
                        - .env
