version: "3"
services:
        web:
                image: chasefarmer94/rumbaugh-art-app:prod
                restart: unless-stopped
        api:
                build: ./server
                ports:
                        - 8081:80
                links:
                        - "lychee:lychee"
                env_file:
                        - .env
                restart: unless-stopped
        lychee:
                build: ./lychee
                ports:
                        - 8080:80
                links:
                        - "mysql:mysql"
                restart: unless-stopped
        mysql:
                build: ./db
                command: --default-authentication-plugin=mysql_native_password
                ports:
                        - 3306:3306
                env_file:
                        - .env
                restart: unless-stopped
        reverse_proxy:
                image: nginx:mainline-alpine
                ports:
                        - 443:443
                        - 80:80
                volumes:
                        - web-root:/var/www/html
                        - ./reverse_proxy:/etc/nginx/conf.d
                        - certbot-etc:/etc/letsencrypt
                        - certbot-var:/var/lib/letsencrypt
                        - ./dhparam:/etc/ssl/certs
                depends_on:
                        - web
                restart: unless-stopped
        certbot:
                image: certbot/certbot
                volumes:
                        - certbot-etc:/etc/letsencrypt
                        - certbot-var:/var/lib/letsencrypt
                        - web-root:/var/www/html
                depends_on:
                        - reverse_proxy
                command: certonly --webroot --webroot-path=/var/www/html --email srumbaugh@srumbaugh.com --agree-tos --no-eff-email -d srumbaugh.com -d www.srumbaugh.com
        stats:
                image: ghcr.io/mikecao/umami:postgresql-latest
                ports:
                        - 3000:80
                environment:
                        DATABASE_URL: postgresql://umami:umami@db:5432/umami
                        DATABASE_TYPE: postgresql
                        HASH_SALT: srumbaugh
                depends_on:
                        - umami-db
        umami-db:
                image: postgres:12-alpine
                environment:
                        POSTGRES_DB: umami
                        POSTGRES_USER: umami
                        POSTGRES_PASSWORD: umami
                volumes:
                        - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
                        - umami-db-data:/var/lib/postgresql/data

volumes:
        certbot-etc:
        certbot-var:
        web-root:
        dhparam:
        umami-db-data:
