version: "3"
services:
        web:
                image: chasefarmer94/rumbaugh-art-app:prod
                restart: unless-stopped
        api:
                build: ./server
                ports:
                        - 8081:80
                links:
                        - "lychee:lychee"
                env_file:
                        - .env
                restart: unless-stopped
        lychee:
                image: lycheeorg/lychee
                ports:
                        - 8080:80
                links:
                        - "lychee_db:lychee_db"
                env_file:
                        - .env
                volumes:
                        - ./lychee/conf:/conf
                        - ./lychee/uploads:/uploads
                        - ./lychee/sym:/sym
                restart: unless-stopped
        lychee_db:
                image: mariadb:10
                # command: --default-authentication-plugin=mysql_native_password
                ports:
                        - 3306:3306
                env_file:
                        - .env
                volumes:
                        - ./db/init:/docker-entrypoint-initdb.d/
                        - ./db/backup:/backup
                        - mysql:/var/lib/mysql
                restart: unless-stopped
        reverse_proxy:
                build: ./reverse_proxy
                ports:
                        - 443:443
                        - 80:80
                volumes:
                        - ./letsencrypt:/etc/letsencrypt
                        - ./dhparam:/etc/ssl/certs
                depends_on:
                        - web
                restart: unless-stopped
volumes:
        mysql:
        dhparam:
        umami-db-data:
