version: "2"
services:
        lychee:
                build: ./lychee
                ports:
                        - 80:80
                links:
                        - "mysql:mysql"
        mysql:
                build: ./db
                command: --default-authentication-plugin=mysql_native_password
                ports:
                        - 3306:3306
                env_file:
                        - .env
