version: "2"
services:
        lychee:
                image: linuxserver/lychee
                ports:
                        - 80:80
                links:
                        - "mysql:mysql"
        mysql:
                image: hypriot/rpi-mysql
                env_file:
                        - .env
